import type { Creator } from "@/types/creator";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const MOCK_CREATORS: Creator[] = [
  {
    id: "mock-01",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Vitória",
    nome: "Rebeca Oliveira",
    tier: "T2",
    segmento: "Beleza",
    perfil_handle: "@rebeca.oliveira",
    contato: true,
    respondido: true,
    status: "Ativou",
    obs: "Super engajada, topou na hora",
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
  },
  {
    id: "mock-02",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Stefanie",
    nome: "Lara Jucah",
    tier: "T1",
    segmento: "Lifestyle",
    perfil_handle: "@larajucah",
    contato: true,
    respondido: false,
    status: "Contatada",
    obs: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "mock-03",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Vitória",
    nome: "Rafaelle Lívia",
    tier: "T2",
    segmento: "Moda",
    perfil_handle: "@rafaellelivia",
    contato: true,
    respondido: true,
    status: "Interessa",
    obs: "Pediu proposta comercial",
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: "mock-04",
    canal: "TikTok",
    pais: "Brasil",
    analista: "Bia",
    nome: "Irena Veneno",
    tier: "Super Star",
    segmento: "Humor",
    perfil_handle: "@irenavenenoo",
    contato: true,
    respondido: true,
    status: "Negociando",
    obs: "Aguardando resposta do jurídico",
    created_at: daysAgo(4),
    updated_at: daysAgo(2),
  },
  {
    id: "mock-05",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Mauricio",
    nome: "Mandatsu Nani",
    tier: "T3",
    segmento: "Gastronomia",
    perfil_handle: "@mandatsunani",
    contato: true,
    respondido: false,
    status: "Prospectada",
    obs: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: "mock-06",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Bia",
    nome: "Agatha Santos",
    tier: "T2",
    segmento: "Fitness",
    perfil_handle: "@agatha.fit",
    contato: true,
    respondido: true,
    status: "Respondeu",
    obs: "Gostou do serviço, quer mais infos",
    created_at: daysAgo(6),
    updated_at: daysAgo(4),
  },
  {
    id: "mock-07",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Stefanie",
    nome: "Jully Poca",
    tier: "T1",
    segmento: "Maternidade",
    perfil_handle: "@jully.poca",
    contato: false,
    respondido: false,
    status: "Prospectada",
    obs: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: "mock-08",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Vitória",
    nome: "Perera Fany",
    tier: "T3",
    segmento: "Beleza",
    perfil_handle: "@pererafany",
    contato: true,
    respondido: true,
    status: "Não quis",
    obs: "Disse que não tem interesse no momento",
    created_at: daysAgo(8),
    updated_at: daysAgo(6),
  },
  {
    id: "mock-09",
    canal: "TikTok",
    pais: "Brasil",
    analista: "Mauricio",
    nome: "Uju Sali Meni",
    tier: "T2",
    segmento: "Games",
    perfil_handle: "@ujusalimeni",
    contato: true,
    respondido: true,
    status: "Contatada",
    obs: null,
    created_at: daysAgo(9),
    updated_at: daysAgo(9),
  },
  {
    id: "mock-10",
    canal: "Instagram",
    pais: "Colômbia",
    analista: "Bia",
    nome: "Carolina Mesa",
    tier: "T1",
    segmento: "Lifestyle",
    perfil_handle: "@carolinamesa.co",
    contato: true,
    respondido: false,
    status: "Contatada",
    obs: "Espanhol — contato via DM",
    created_at: daysAgo(10),
    updated_at: daysAgo(10),
  },
  {
    id: "mock-11",
    canal: "YouTube",
    pais: "Brasil",
    analista: "Stefanie",
    nome: "Lucas Gamer",
    tier: "T4",
    segmento: "Games",
    perfil_handle: "@lucasgamer",
    contato: true,
    respondido: true,
    status: "Já tem conta",
    obs: "Já é cliente desde 2024",
    created_at: daysAgo(12),
    updated_at: daysAgo(12),
  },
  {
    id: "mock-12",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Vitória",
    nome: "Mari Flores",
    tier: "T2",
    segmento: "Moda",
    perfil_handle: "@mariflores",
    contato: true,
    respondido: true,
    status: "Ativou",
    obs: null,
    created_at: daysAgo(13),
    updated_at: daysAgo(11),
  },
  {
    id: "mock-13",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Bia",
    nome: "Fernanda Lima",
    tier: "T1",
    segmento: "Beleza",
    perfil_handle: "@fernandalima.beauty",
    contato: true,
    respondido: true,
    status: "Interessa",
    obs: "Quer proposta para 3 meses",
    created_at: daysAgo(14),
    updated_at: daysAgo(10),
  },
  {
    id: "mock-14",
    canal: "Kwai",
    pais: "Brasil",
    analista: "Mauricio",
    nome: null,
    tier: "T4",
    segmento: "Humor",
    perfil_handle: "@kwaifunny123",
    contato: false,
    respondido: false,
    status: "Prospectada",
    obs: null,
    created_at: daysAgo(15),
    updated_at: daysAgo(15),
  },
  {
    id: "mock-15",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Stefanie",
    nome: "Ana Paula Costa",
    tier: "T2",
    segmento: "Educação",
    perfil_handle: "@anapaulacosta.edu",
    contato: true,
    respondido: false,
    status: "Contatada",
    obs: null,
    created_at: daysAgo(16),
    updated_at: daysAgo(16),
  },
  {
    id: "mock-16",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Vitória",
    nome: "Thaís Drummond",
    tier: "Super Star",
    segmento: "Fitness",
    perfil_handle: "@thaisdrummond",
    contato: true,
    respondido: true,
    status: "Negociando",
    obs: "High value — prioridade",
    created_at: daysAgo(18),
    updated_at: daysAgo(14),
  },
  {
    id: "mock-17",
    canal: "TikTok",
    pais: "Colômbia",
    analista: "Bia",
    nome: "Valentina Cruz",
    tier: "T3",
    segmento: "Moda",
    perfil_handle: "@valentina.cruz.co",
    contato: true,
    respondido: true,
    status: "Respondeu",
    obs: "Interesse em plano mensal",
    created_at: daysAgo(20),
    updated_at: daysAgo(18),
  },
  {
    id: "mock-18",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Mauricio",
    nome: "Bianca Nunes",
    tier: "T2",
    segmento: "Maternidade",
    perfil_handle: "@biancanunes.mae",
    contato: true,
    respondido: false,
    status: "Prospectada",
    obs: null,
    created_at: daysAgo(22),
    updated_at: daysAgo(22),
  },
  {
    id: "mock-19",
    canal: "Instagram",
    pais: "Brasil",
    analista: "Stefanie",
    nome: "Priscila Rocha",
    tier: "T1",
    segmento: "Beleza",
    perfil_handle: "@priscilarocha",
    contato: true,
    respondido: true,
    status: "Ativou",
    obs: "Converteu rápido",
    created_at: daysAgo(25),
    updated_at: daysAgo(23),
  },
];
